server {
    listen       80;
    listen       [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Handles routing untuk root URL dan semua subfolder (termasuk /under-construction)
    location / {
        try_files $uri $uri/ =404;
    }

    # Proteksi folder error agar hanya dipanggil internal oleh Nginx/Traefik
    location /errors/ {
        internal;
    }

    # Custom Error Pages
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}